server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: C:/Users/jaivb/Desktop/INFO8665--Airplane/promtail-positions.yaml

clients:
  - url: ${CLOUD_HOSTED_LOGS_URL}
    basic_auth:
      username:  ${GRAFANA_USERNAME}
      password: ${GRAFANA_API_KEY}

scrape_configs:
  - job_name: airfare_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: airfare_logs
          __path__: C:\\Users\\jaivb\\Desktop\\INFO8665--Airplane\\logs\\*.log

